# CMake generated Testfile for 
# Source directory: /Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D
# Build directory: /Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[MIR4D_BuildCheck]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_BuildCheck")
set_tests_properties([=[MIR4D_BuildCheck]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;287;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_Integration4D]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_Integration4D")
set_tests_properties([=[MIR4D_Integration4D]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;288;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_StlRoundTrip]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_StlRoundTrip")
set_tests_properties([=[MIR4D_StlRoundTrip]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;289;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_StepImporter]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_StepImporter")
set_tests_properties([=[MIR4D_StepImporter]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;290;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_AssimpImport]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_AssimpImport")
set_tests_properties([=[MIR4D_AssimpImport]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;292;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_DocumentRenderBridge]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_DocumentRenderBridge")
set_tests_properties([=[MIR4D_DocumentRenderBridge]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;294;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_RenderCamera]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_RenderCamera")
set_tests_properties([=[MIR4D_RenderCamera]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;295;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_RayPicker]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_RayPicker")
set_tests_properties([=[MIR4D_RayPicker]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;296;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_CreateBox]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_CreateBox")
set_tests_properties([=[MIR4D_CreateBox]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;297;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_ObjectStore]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_ObjectStore")
set_tests_properties([=[MIR4D_ObjectStore]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;298;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_EngineDocumentBridge]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_EngineDocumentBridge")
set_tests_properties([=[MIR4D_EngineDocumentBridge]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;299;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_BRepBox]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_BRepBox")
set_tests_properties([=[MIR4D_BRepBox]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;300;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_BRepTopology]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_BRepTopology")
set_tests_properties([=[MIR4D_BRepTopology]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;301;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_BRepProfileExtrude]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_BRepProfileExtrude")
set_tests_properties([=[MIR4D_BRepProfileExtrude]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;302;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_BRepHeaderCheck]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_BRepHeaderCheck")
set_tests_properties([=[MIR4D_BRepHeaderCheck]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;303;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_BRepBoolean]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_BRepBoolean")
set_tests_properties([=[MIR4D_BRepBoolean]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;304;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_GeometryQuery]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_GeometryQuery")
set_tests_properties([=[MIR4D_GeometryQuery]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;305;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_SketchRectangleProfile]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_SketchRectangleProfile")
set_tests_properties([=[MIR4D_SketchRectangleProfile]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;306;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_SketchRectangleSolver]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_SketchRectangleSolver")
set_tests_properties([=[MIR4D_SketchRectangleSolver]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;307;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_WorkPlane]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_WorkPlane")
set_tests_properties([=[MIR4D_WorkPlane]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;308;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_SketchDocumentSolver]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_SketchDocumentSolver")
set_tests_properties([=[MIR4D_SketchDocumentSolver]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;309;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_ViewportFoundation]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_ViewportFoundation")
set_tests_properties([=[MIR4D_ViewportFoundation]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;310;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_ViewportRuntime]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_ViewportRuntime")
set_tests_properties([=[MIR4D_ViewportRuntime]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;311;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_ViewportController]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_ViewportController")
set_tests_properties([=[MIR4D_ViewportController]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;312;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_Count]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_Count")
set_tests_properties([=[MIR4D_Count]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;313;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_Simulation]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_Simulation")
set_tests_properties([=[MIR4D_Simulation]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;314;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_CAESimulation]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_CAESimulation")
set_tests_properties([=[MIR4D_CAESimulation]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;315;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_CAETest]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_CAETest")
set_tests_properties([=[MIR4D_CAETest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;316;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_CAECampaign]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_CAECampaign")
set_tests_properties([=[MIR4D_CAECampaign]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;317;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_CAEController]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_CAEController")
set_tests_properties([=[MIR4D_CAEController]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;318;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_CAEJson]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_CAEJson")
set_tests_properties([=[MIR4D_CAEJson]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;319;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_CAELoad]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_CAELoad")
set_tests_properties([=[MIR4D_CAELoad]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;320;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_CAEExport]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_CAEExport")
set_tests_properties([=[MIR4D_CAEExport]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;321;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_ExtendedDomains]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_ExtendedDomains")
set_tests_properties([=[MIR4D_ExtendedDomains]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;322;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_SceneCommandHistory]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_SceneCommandHistory")
set_tests_properties([=[MIR4D_SceneCommandHistory]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;323;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_SelectionState]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_SelectionState")
set_tests_properties([=[MIR4D_SelectionState]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;324;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
add_test([=[MIR4D_MathNumeric]=] "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/build-asan/MIR4D_MathNumeric")
set_tests_properties([=[MIR4D_MathNumeric]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;325;add_test;/Users/sergejstepovoj/Desktop/mir4d/GitHubMir4D/CMakeLists.txt;0;")
subdirs("MirUI")
