import Foundation
import simd

/// Renderer- and kernel-independent deformation field generated by hand contact.
struct MIRAirDeformationField: Equatable, Sendable {
    enum Mode: String, Sendable {
        case push
        case pull
        case smooth
    }

    var center: SIMD3<Double>
    var normal: SIMD3<Double>
    var radius: Double
    var strength: Double
    var displacement: Double
    var falloff: Double
    var mode: Mode

    init(center: SIMD3<Double>, normal: SIMD3<Double>, radius: Double, strength: Double, displacement: Double, falloff: Double = 2, mode: Mode) {
        self.center = center
        self.normal = simd_normalize(normal)
        self.radius = max(radius, 0.0001)
        self.strength = min(max(strength, 0), 1)
        self.displacement = displacement
        self.falloff = max(falloff, 0.1)
        self.mode = mode
    }

    func influence(at point: SIMD3<Double>) -> Double {
        let distance = simd_distance(point, center)
        guard distance < radius else { return 0 }
        let normalizedDistance = 1 - distance / radius
        return pow(max(0, min(1, normalizedDistance)), falloff) * strength
    }

    func displacement(at point: SIMD3<Double>) -> SIMD3<Double> {
        let weight = influence(at: point)
        guard weight > 0, mode != .smooth else { return .zero }
        let sign: Double = mode == .push ? 1 : -1
        return normal * (abs(displacement) * weight * sign)
    }
}

/// Applies an air field to a position buffer without knowing anything about rendering or UI.
struct MIRAirPositionDeformer: Sendable {
    func applying(_ field: MIRAirDeformationField, to positions: [SIMD3<Double>]) -> [SIMD3<Double>] {
        positions.map { $0 + field.displacement(at: $0) }
    }
}
