
#pragma once

#include "LinearSystem.hpp"
#include "NumericalAnalysis.hpp"
#include "Interpolation.hpp"
#include "Statistics.hpp"
#include "Random.hpp"
#include "Eigen.hpp"
#include "Optimization.hpp"
#include "Decomposition.hpp"
#include "Derivatives.hpp"
#include "Svd.hpp"
#include "Distributions.hpp"
#include "Ode.hpp"
#include "Polynomials.hpp"
#include "Fft.hpp"
#include "Transforms.hpp"
#include "SpecialFunctions.hpp"
#include "Iterative.hpp"
#include "Pde.hpp"
#include "Sparse.hpp"
#include "Splines.hpp"
